'use client';

import React from 'react';
import Navbar from '@/components/Navbar';
import SellerBottomNav from '@/components/SellerBottomNav';
import { Download, Globe, ShieldCheck, ExternalLink, FileSpreadsheet, Building2, Landmark } from 'lucide-react';

export default function MarketConnectionsPage() {
  const handleDownloadCsv = () => {
    window.open('/api/market-connections/export', '_blank');
  };

  return (
    <div className="min-h-screen bg-[#FAF8F3] font-sans text-[#243B53] pb-24">
      <Navbar />

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        
        {/* Banner */}
        <div className="bg-gradient-to-r from-[#243B53] to-[#1a2c3f] text-white p-6 md:p-8 rounded-3xl shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-6 border-b-4 border-[#C65D3B]">
          <div>
            <span className="text-xs font-bold bg-[#C65D3B] text-white px-3 py-1 rounded-full uppercase">
              Market Pathways & Connectivity
            </span>
            <h1 className="text-3xl font-black mt-2">Government & Export Connections</h1>
            <p className="text-xs text-[#F4EBDD]/80 mt-1">Export your artisan catalog for GeM, ONDC, and institutional buyer procurement.</p>
          </div>

          <button
            onClick={handleDownloadCsv}
            className="btn-touch btn-terracotta text-base shadow-lg flex items-center gap-2 hover:scale-105 transition-transform shrink-0"
          >
            <Download className="w-5 h-5" /> Download GeM Catalog (CSV)
          </button>
        </div>

        {/* GUIDED PATHWAYS GRID */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* GeM Government e-Marketplace */}
          <div className="soft-card p-6 bg-white space-y-4 border-l-4 border-l-[#243B53]">
            <div className="w-12 h-12 rounded-2xl bg-[#243B53] text-white flex items-center justify-center">
              <Landmark className="w-7 h-7 text-[#F4EBDD]" />
            </div>
            <h3 className="text-lg font-bold text-[#243B53]">GeM (Government e-Marketplace)</h3>
            <p className="text-xs text-gray-600 leading-relaxed">
              Official procurement portal for Central & State Government departments. Standardized product parameters generated by HASTRA enable direct onboarding.
            </p>
            <a
              href="https://gem.gov.in"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-bold text-[#C65D3B] hover:underline"
            >
              Official GeM Portal <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>

          {/* ONDC Open Network */}
          <div className="soft-card p-6 bg-white space-y-4 border-l-4 border-l-[#C65D3B]">
            <div className="w-12 h-12 rounded-2xl bg-[#C65D3B] text-white flex items-center justify-center">
              <Globe className="w-7 h-7" />
            </div>
            <h3 className="text-lg font-bold text-[#243B53]">ONDC Handloom Network</h3>
            <p className="text-xs text-gray-600 leading-relaxed">
              Open Network for Digital Commerce allows Indian handloom weavers to list products across multiple national buyer apps seamlessly.
            </p>
            <a
              href="https://ondc.org"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-bold text-[#C65D3B] hover:underline"
            >
              Official ONDC Portal <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>

          {/* Export Catalog Generator */}
          <div className="soft-card p-6 bg-white space-y-4 border-l-4 border-l-[#3E6650]">
            <div className="w-12 h-12 rounded-2xl bg-[#3E6650] text-white flex items-center justify-center">
              <FileSpreadsheet className="w-7 h-7" />
            </div>
            <h3 className="text-lg font-bold text-[#243B53]">Export Catalog Generator</h3>
            <p className="text-xs text-gray-600 leading-relaxed">
              Generate standardized Excel/CSV catalog files formatted for international handicraft expos, trade fairs, and wholesale export houses.
            </p>
            <button
              onClick={handleDownloadCsv}
              className="inline-flex items-center gap-1.5 text-xs font-bold text-[#3E6650] hover:underline"
            >
              Generate Export CSV File <Download className="w-3.5 h-3.5" />
            </button>
          </div>

        </div>

      </main>

      <SellerBottomNav />
    </div>
  );
}
